// TABLE NAME
const tableWeather = 'weather';

// TABLE COLUMN NAMES
const tblWeatherColId = 'id';
const tblWeatherColLon = 'lon';
const tblWeatherColLat = 'lat';
const tblWeatherColWeatherId = 'weatherId';
const tblWeatherColWeatherMain = 'weatherMain';
const tblWeatherColWeatherDescription = 'weatherDescription';
const tblWeatherColWeatherIcon = 'weatherIcon';
const tblWeatherColBase = 'base';
const tblWeatherColTemp = 'temp';
const tblWeatherColFeelsLike = 'feelsLike';
const tblWeatherColTempMin = 'tempMin';
const tblWeatherColTempMax = 'tempMax';
const tblWeatherColPressure = 'pressure';
const tblWeatherColHumidity = 'humidity';
const tblWeatherColSeaLevel = 'seaLevel';
const tblWeatherColGrndLevel = 'grndLevel';
const tblWeatherColWindSpeed = 'windSpeed';
const tblWeatherColWindDeg = 'windDeg';
const tblWeatherColWindGust = 'windGust';
const tblWeatherColCloudAll = 'cloudAll';
const tblWeatherColDt = 'dt';
const tblWeatherColSysType = 'sysType';
const tblWeatherColSysId = 'sysId';
const tblWeatherColSysCountry = 'sysCountry';
const tblWeatherColSysSunrise = 'sysSunrise';
const tblWeatherColSysSunset = 'sysSunset';
const tblWeatherColTimezone = 'timezone';
const tblWeatherColName = 'name';
const tblWeatherColCod = 'cod';
